name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk python3-pip git
        pip install --upgrade pip
        pip install buildozer cython
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: bin/*.apk